max_num: -1
obj_mass: 0.1   # unit: kg 
miu_coef: [0.6, 0.02]
debug_render: False
debug_viewer: True
debug_dir: ${save_dir}/debug

simulation_metrics: 
  max_pene: 0.005  # If the initial hand penetrates the object too much, regard it as a failure
  max_force: 1.0
  trans_thre: 0.05
  angle_thre: 15

analytic_fc_metrics: 
  contact_tip_only: True 
  contact_threshold: 0.005
  type: ['qp', 'qp_dfc', 'q1', 'tdg', 'dfc']

pene_contact_metrics: 
  contact_margin: 0.01  # unit: m. Max contact distance.
  contact_threshold: 0.002

# added by mingrui
with_approaching: False
arm_pregrasp_is_grasp: True
method: "op" # "op" or "ours"
input_data: "succ_dir" # "grasp_dir" or "succ_dir"

graspdata:
  pregrasp_t: 2 # >0
  squeeze_t: 0 # >0

# params of our controller
control:
  ablation_name: "ab2" # 'ab0' to 'abx'

  free_stage_switch: True # fixed
  stage2_after_full_path: True # fixed
  desired_sum_force_as_traj: True # fixed
  use_desired_sum_force_ub: True # fixed
  stage2_incontact_force_only: True # fixed
  stage2_penalize_tan_motion: False # fixed
  balance_use_normalized: True # fixed
  stage1_force_thres: 0.2 # fixed
  Kr_use_two_jaco_a: False # fixed
  stage2_Ks_hand_only: True # fixed
  Kp_scale: 1.0 # fixed

  stage2_tan_force_constraint: False
  stage2_ctrl_tan_force: True
  
  stage2_increase_force: False # cartesian-space
  stage2_joint_increase_force: False # tau = Kp * delta q
  stage2_joint_increase_force_2: False # tau = J.T * F
  
  stage2_equal_force_cost: False # cartesian-space
  stage2_equal_joint_force_cost: True
  
  Ke_scalar: 1e5 # approximate in mujoco: 1e5-1e6 (GPT)
  use_coupling: False # must be False in theory
  tan_motion_pen_weight: 1e3 # DEBUG

  ab0: # no consideration of tan force
    stage2_tan_force_constraint: False
    stage2_ctrl_tan_force: False

    stage2_increase_force: False
    stage2_equal_joint_force_cost: True
    Ke_scalar: 1e5

  ab1: # strictly consider tan force
    stage2_tan_force_constraint: True
    stage2_ctrl_tan_force: False

    stage2_increase_force: False
    stage2_equal_joint_force_cost: True
    Ke_scalar: 1e5

  ab2: # softly consider tan force
    stage2_tan_force_constraint: False
    stage2_ctrl_tan_force: True

    stage2_increase_force: False
    stage2_equal_joint_force_cost: True
    Ke_scalar: 1e5

  ab3: # no equal joint force cost
    stage2_tan_force_constraint: False
    stage2_ctrl_tan_force: True

    stage2_increase_force: False
    stage2_equal_joint_force_cost: False
    Ke_scalar: 1e5

  ab4: # add stage2_increase_force
    stage2_tan_force_constraint: False
    stage2_ctrl_tan_force: True

    stage2_increase_force: True
    stage2_equal_joint_force_cost: True
    Ke_scalar: 1e5

  ab6: # free_stage_switch is False
    stage2_tan_force_constraint: False
    stage2_ctrl_tan_force: True
    stage2_increase_force: False
    stage2_equal_joint_force_cost: True
    Ke_scalar: 1e5
    free_stage_switch: False

  ab7: # coupling
    stage2_tan_force_constraint: False
    stage2_ctrl_tan_force: True
    stage2_increase_force: False
    stage2_equal_joint_force_cost: True
    use_coupling: True
    Ke_scalar: 1e5
    tan_motion_pen_weight: 1e2
  

# evaluation setting
offsets: [0.0] # unit: m


