max_num: -1
obj_mass: 0.1   # unit: kg 
miu_coef: [0.6, 0.02]
debug_render: False
debug_viewer: True
debug_dir: ${save_dir}/debug

simulation_metrics: 
  max_pene: 0.005  # If the initial hand penetrates the object too much, regard it as a failure
  max_force: 1.0
  trans_thre: 0.05
  angle_thre: 15

analytic_fc_metrics: 
  contact_tip_only: True 
  contact_threshold: 0.005
  type: ['qp', 'qp_dfc', 'q1', 'tdg', 'dfc']

pene_contact_metrics: 
  contact_margin: 0.01  # unit: m. Max contact distance.
  contact_threshold: 0.002

# added by mingrui
with_approaching: False
arm_pregrasp_is_grasp: True
method: "op" # "open_loop" or "ours"
input_data: "succ_dir" # "grasp_dir" or "succ_dir"

graspdata:
  pregrasp_t: 2 # >0
  squeeze_t: 0 # >0

# params of our controller
control:
  free_stage_switch: True

# evaluation setting
offsets: [0.02]


