max_num: -1
obj_mass: 0.1   # unit: kg 
miu_coef: [0.6, 0.02]
debug_render: True
debug_viewer: True
debug_dir: ${save_dir}/debug

simulation_metrics: 
  max_pene: 0.01  # If the initial hand penetrates the object too much, regard it as a failure
  trans_thre: 0.05
  angle_thre: 15

analytic_fc_metrics: 
  contact_tip_only: True 
  contact_threshold: 0.005
  type: ['qp', 'qp_dfc', 'q1', 'tdg', 'dfc']

pene_contact_metrics: 
  contact_margin: 0.01  # unit: m. Max contact distance.
  contact_threshold: 0.002

